### PR TITLE
Now I Have 2 Problems: On Building a PDF & HTML Annotator in a Chrome…

### PR DESCRIPTION
**Pull request by RichardLitt**
… Extension

This is the story of building [Beagle](https://github.com/BeagleLab/beagle) with the MIT Media Lab. Beagle is a PDF and HTML annotator in a Chrome Extension, using Browserify, React, Oauth, and PDFjs. I've learned a ton trying to jerry rig this project together, and would like to talk about how I problem solved some issues that came up - for instance, how do you deal with different React components for different types of documents? How do you get Oauth to work without a popup? How do you sync offline using Pouch and Couch and localStorage? How do you deal with Chrome's native PDF API (short answer; you don't, it doesn't exist). Instead of going through and answering these questions directly, I'll retell what I tried, what worked, and what didn't.

### CODE REVIEW

**Comment by jed** [comment]
Heya @RichardLitt, thanks for the talk proposal! Alas, we've filled up our speaking slots for October, but would you mind if we keep this submission open for consideration in future events?

If you'd still like to attend this month with a reserved ticket, please ping @kosamari at the email listed in her profile!

**Comment by RichardLitt** [comment]
I wouldn't mind. I kind of feel like it should be written better, and that I am not good at writing these things. Any ideas on that? Anyone I can talk to about making better talks?

**Comment by jed** [comment]
I think the proposal was fine, personally, but it never hurts to talk more about the narrative if it's going to be a narrative talk (which this one seems to be). One issue is that our format is really short (10 minutes!) and it might be worth it to distill this path into something more succinct, so that the audience can absorb more.

**Comment by RichardLitt** [comment]
Cool. I'll work on cutting it down. Thanks!

**Pull request closed without merging**
