### PR TITLE
Speaker numero dos

### PR DESCRIPTION
**Pull request by sranso**
What does it mean to write functional code versus object oriented code in js? Is there another "way" to write js code (or any code)? Let's talk about it, look at some examples, have some laughs.

### CODE REVIEW

**Comment by jed** [comment]
that's so ranso!

**Comment by sranso** [comment]
so ranso raven!

**Comment by cassidoo** [comment]
Oh man if you had a talk about futures in JS you could totally continue this joke with the next line, "it's the future I can see"

**Comment by terriburns** [comment]
omg @sranso you're my hero

**Pull request merged**
