### PR TITLE
Proposal: Rethinking the Browser

### PR DESCRIPTION
**Pull request by pfrazee**
[Beaker](https://beakerbrowser.com) is an experimental fork of Chrome. It's being created in collaboration with the [Dat project](http://dat-data.com/about) to integrate peer-to-peer protocols and APIs into the Web.

I'd like to demo the browser, share some of our ideals and ideas for the future, and talk about as many technical decisions as I can in 10 minutes. I'll discuss how Dat works, why we're not using blockchains, and how we can make the browser more OS-like, starting with breaking the host/client relationship.

Overview of the talk:

 - Short history
 - Demo & technical overview of Dat's protocol
 - Ideas for our future

### CODE REVIEW

**Comment by pfrazee** [comment]
I should mention I'll be traveling from out of town, and my schedule is flexible, so I can speak in November if October is full.

**Comment by paladique** [comment]
Thank your for your proposal! We have decided on our speaker lineup and couldn't fit this one in this month. You get first dibs on tickets, email organizers@brooklynjs.com for details! Hope to see you there!

**Comment by dmvaldman** [comment]
That's too bad. I would have wanted to see this. @pfrazee if you're talking about it elsewhere in your time here let me know.

**Comment by pfrazee** [comment]
@dmvaldman I did schedule a talk at NY Serverless. Slightly different theme to fit their meetup, but same overall content. There's a waitlist, but add yourself just in case: https://www.meetup.com/Serverless-NYC/events/234738007/

**Pull request closed without merging**
