### PR TITLE
Proposal: What is "serverless" even?

### PR DESCRIPTION
**Pull request by pselle**
The "cloud" is a [mere construct in our minds](https://d21ii91i3y6o6h.cloudfront.net/gallery_images/from_proof/3442/large/1418280711/die-cut-stickers.png), but those wild kids are taking things further with "serverless" apps. Now you don't even have an imaginary server – you can run "serverless"!

Serverless is the ~~possible~~ solution to the monolith => microservices => **how do we run all of these things** problem. Using on-demand computation (ex. AWS Lambda), your code no longer lives on a box somewhere, but instead ... lives on a box somewhere **_but_** you only pay for the time it takes to execute. It's pretty neat!

In this talk, you'll learn what is serverless even, what various systems and terms people are talking about, and we'll deploy on on-demand function together, in Node.js bien sûr.

### CODE REVIEW

**Comment by kosamari** [comment]
Pam !  thank you ❤️ for submitting! Unfortunately we had 3X submission this month and full up all spot...

Hope you can come up to NYC in another month to give server less talk !

Please ping me on 📧  (address on my profile page) about your reserved ticket if you can still join us 💁

**Comment by pselle** [comment]
Thanks! Looking forward to attending. Saw lots of great proposals!

**Comment by pselle** [comment]
Reopening for August!

**Comment by kosamari** [comment]
Yaaaaay ! 👍 
Can't wait to have you back in Brooklyn :) ✉️ 🔜

**Pull request closed without merging**
