### PR TITLE
It's about Time

### PR DESCRIPTION
**Pull request by dcousineau**
No seriously, it's about time. The short description is I want to rant for 10 minutes on time and how it's a BS social construct. The long description is I want to talk about the complexities of time handling in applications. This is not a talk that ends with answers but more like it ends with a checklist and a reminder to _really_ spend 3x the time you normally would have really cementing and thinking about anything related to time in your applications.

### CODE REVIEW

**Comment by willmanduffy** [comment]
we are busy

**Comment by dcousineau** [comment]
@willmanduffy if there's anyone who needs help with calendars....

**Comment by paladique** [comment]
We said we are busy :imp:

**Comment by paladique** [comment]
jk resubmit next month :heart:

**Pull request closed without merging**
