### PR TITLE
Talk proposal for brooklynjs by Sean R.

### PR DESCRIPTION
**Pull request by seanreed1111**
A few of the pain points of a newbie to RxJS, discovered by using it to code a simple game.

### CODE REVIEW

**Comment by kosamari** [comment]
sounds awesome, looking forward to seeing your talk. Will send you email with ticket & details 🔜

**Comment by seanreed1111** [comment]
Excellent! But, I managed to buy a ticket this morning at 10 on the dot. Give it away to a broke freelancer..

**Comment by seanreed1111** [comment]
Ooh, even better, can I run some sort of poll/contest to give it away to promote the talk?? Or just give it away to a friend for moral support??

**Comment by brianloveswords** [comment]
@seanreed1111 you can definitely give it away to a friend for moral support, or really do whatever you want with the ticket you bought!

**Comment by seanreed1111** [comment]
Ok cool, thanks! Will maybe do a little mini charity auction for my own charity http://littlestembooks.org or just give it away if not enough interest...
Time to start writing!

**Pull request closed without merging**
