### PR TITLE
WebWorkers talk proposal

### PR DESCRIPTION
**Pull request by nolanlawson**
(I utterly failed to come up with a good "work" pun, so please feel free to replace the promo text with something better. :smiley:)

Basically, I would like to give a talk on WebWorkers, why I think they're so awesome, and how they can save us from janky webapps that don't run well on mobile devices. I plan on mostly combining ideas from [this blog post](http://www.pocketjavascript.com/blog/2015/11/23/introducing-pokedex-org) and [this talk](https://www.youtube.com/watch?v=okk0BGV9oY0), with maybe some details from [this post](http://nolanlawson.com/2015/09/29/indexeddb-websql-localstorage-what-blocks-the-dom/) if I have time.

### CODE REVIEW

**Comment by dmvaldman** [comment]
I have no actual say, but giving this talk and the OP's work on Pokedex a :+1:

**Comment by bahmutov** [comment]
should be good one :100:

**Comment by kosamari** [comment]
:100: 
sending you speaker details later via email!

**Comment by nolanlawson** [comment]
Yay! Looking forward to BrooklynJS. :)

**Pull request closed without merging**
