### PR TITLE
talk submission #2!

### PR DESCRIPTION
**Pull request by toddself**
A lot of people are spooked out and frightened by the built-in node debugger.  They shouldn't be!  A live-exercise in debugging via the console for your node applications!

### CODE REVIEW

**Comment by jed** [comment]
see https://github.com/brooklynjs/brooklynjs.github.io/pull/195#issuecomment-141535168

**Comment by toddself** [comment]
i have two talks i've been working on so i figured i'd submit them both!

**Comment by kosamari** [comment]
:+1:
based on @toddself 's wonderful "Todd as a service" work in Boro.js community.

**Comment by jed** [comment]
We decided to go with https://github.com/brooklynjs/brooklynjs.github.io/pull/195#issuecomment-141535168!

**Pull request closed without merging**
