### PR TITLE
EON.js talk proposal

### PR DESCRIPTION
**Pull request by elizabethsiegle**
# Talk proposal: 
_How to use PubNub's [Project EON.js ](https://www.pubnub.com/developers/eon/)framework to easily make realtime charts and graphs._

### CODE REVIEW

**Comment by kosamari** [comment]
@elizabethsiegle hey ya - we generally like to see the project people made, rather than `how to` talks.
(you can totally include hot to steps in your talk, but we love the talk to be centered around story.)

Can you give us what kind of application you made with "realtime charts and graphs" ?? :)

**Comment by elizabethsiegle** [comment]
Just updated index.html with the project!

**Comment by elizabethsiegle** [comment]
Outline:
1. What is Project [EON](https://www.pubnub.com/developers/eon/)? Why is it helpful/useful/relevant to developers? 
-> It is an open-sourced, web-based real-time chart/graph data visualization framework that lets you easily customize your visualization with a variety of chart types, themes, markers, and more. The chart builder tool makes it so you may not even have to write a line of code, unless you wanted to really customize your visualization!  Realtime data could include weather, stocks, geolocation, or tweets...
2. How did I use EON? My [project](https://github.com/pubnub/warriorsDataEon) is a realtime data visualization of tweets about the Warriors during the NBA Finals.
3. A quick overview of an [iOS app](https://github.com/pubnub/swift-apple-watch-heart-rate-pubnub-eon) that uses a webview to display heart rate from the Apple Watch. Though EON is a web-based framework, it is easy to use this web-based framework across platforms.
4. Live coding demo on building an NYC sports team data visualization from tweets.

**Comment by paladique** [comment]
Thank your for your proposal! We have decided on our speaker lineup and couldn't fit this one in this month. You get first dibs on tickets, email organizers@brooklynjs.com for details! Hope to see you there!

**Pull request closed without merging**
