### PR TITLE
Caroline Sinders/Social Media Break Up Coordinator

### PR DESCRIPTION
**Pull request by csinders**
I've spent the past two years studying social media algorithms, harassment, and online communities. I created a performance art piece called "Social Media Break Up Coordinator" where I give users advice about their social media practices. I'm part life coach, part SEO specialists. But the advice is all algorithmically driven. Users fill out a 21 point quiz, and depending upon what they say, I give them specific, automated responses. This project is also a way for me to collect data around how people use social media, and how connected people are to the privacy policies of social media. I was really interested in seeing what people would say and if they would pay me to be an emotional mechanical turk. The project is also inspired by the sharing economy with the wondering of should we outsource certain things, and emotional hardships to someone, and can we automate that? It's incredibly hard to automate emotion with an algorithm, but it's a lot easier to intervene as a human. This project fits in-between those spaces- part human, and part algorithm, but all designed to fit into the spaces where social media breaks down and falls us, and a new person or thing can step in and help mitigate- be it a work problem, family, friendship or romantic.

### CODE REVIEW

**Comment by kosamari** [comment]
@csinders Thanks for submission !  would love to see you on Feb 18th. Sending email about details later tonight !

**Comment by csinders** [comment]
oh! yay!

does this mean i got it??

:)

On Thu, Feb 4, 2016 at 7:29 PM, Mariko Kosaka <notifications@github.com>
wrote:

> Closed #243 <https://github.com/brooklynjs/brooklynjs.github.io/pull/243>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brooklynjs/brooklynjs.github.io/pull/243#event-540022280>
> .
>



-- 
Caroline Sinders
interaction designer, researcher, artist
caroline-sinders.squarespace.com
713-203-0116

**Comment by kosamari** [comment]
yep! just sent you email with details ! :)

**Comment by csinders** [comment]
rad, just got it!

i'd love to attend boroughramming that day :)

On Thu, Feb 4, 2016 at 8:51 PM, Mariko Kosaka <notifications@github.com>
wrote:

> yep! just sent you email with details ! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brooklynjs/brooklynjs.github.io/pull/243#issuecomment-180151480>
> .
>



-- 
Caroline Sinders
interaction designer, researcher, artist
caroline-sinders.squarespace.com
713-203-0116

**Pull request closed without merging**
