### PR TITLE
Web app without custom backend

### PR DESCRIPTION
**Pull request by saturnism**
A quick primer on using Firebase to build rich web application not only capable of storing and retrieving data, but also propagate data updates in real-time. Will live-code a real-time chat web app without a custom backend. It's also super cool when used w/ Polymer (or Angular).

### CODE REVIEW

**Comment by kosamari** [comment]
Wow, no custom backend and wrap in Polymer components sounds very interesting way to make an app ! Would that make front-end app like... just one line of HTML tag??   Unfortunately, we're out of room this month. We'll email you about reserved ticket.

**Comment by wentin** [comment]
among all proposals, this one was the one I wanted to go. Used firebase once, and it was empowering, especially for people with less backend experience, and want to build their own product. If you are giving this talk elsewhere, please let me know.

**Comment by saturnism** [comment]
thanks! will keep trying =)

@wentin I'll keep you posted.  I recall seeing your underscore.js demo from nytm!

**Comment by kosamari** [comment]
Hey @saturnism our talk proposal close on 4/2, maybe interested in submitting it again? thanks !

**Comment by saturnism** [comment]
I'd love to!  But I'll be traveling on 4/16 =(  I will try again for May!

**Comment by kosamari** [comment]
:+1:

**Pull request closed without merging**
