### PR TITLE
talk submission #1

### PR DESCRIPTION
**Pull request by toddself**
This is likely going to be hard to do in 10 minutes, but I want to touch on Operational Transform and Differential Sync which are both strategies for keeping mutated state synced across multiple clients (like how google docs or, well, scripto! works)

### CODE REVIEW

**Comment by jed** [comment]
meh, pass.

**Comment by philduffy** [comment]
TODDDDDDDDDDDDDDD

**Comment by kosamari** [comment]
So the plan is to use BrooklynJS time as Scripto knowledge sharing. 
LGTM but only me :P

**Comment by toddself** [comment]
actually just don't want to have to remember to wake up early on the west coast to try and buy a ticket for boroughgramming.

**Comment by brianloveswords** [comment]
who dis

**Comment by jed** [comment]
Thanks @toddself, we're psyched to have you! Please get in touch with @kosamari to get your ticket, cool? Do you know how to get in touch with her?

**Comment by toddself** [comment]
Thanks everybody!  Can you make an intro for me to @kosamari?  I don't think I've ever met her

**Comment by jed** [comment]
@kosamari, this is @toddself.
@toddself, this is @kosamari.

**Pull request merged**
