### PR TITLE
exquisite texts: second time around

### PR DESCRIPTION
**Pull request by janecakemaster**
exquisite texts: an exquisite corpse poetic experiment
exquisitetexts.com

### CODE REVIEW

**Comment by janecakemaster** [comment]
can this be for september?

**Comment by jed** [comment]
cool, we'll leave this open for september!

**Comment by janecakemaster** [comment]
hi! do you need more info from me?

**Comment by kosamari** [comment]
@janecakemaster Jane we filled up our spots sorry 😭, can we leave this PR open for future events??

ping me about your 1st dibs ticket !

**Comment by janecakemaster** [comment]
​sure​

**Comment by jed** [comment]
Thanks @janecakemaster, we're psyched to have you! Please get in touch with @kosamari to get your ticket, cool?

**Comment by janecakemaster** [comment]
OH SNAP

**Pull request closed without merging**
