### PR TITLE
Web MIDI: Making Browser Music

### PR DESCRIPTION
**Pull request by eric-wood**
Since its inception in 1982, MIDI has been the defacto protocol for musical instruments. Nearly every single electronic instrument (and many other weird creations) since then speak it.

...and for some inexplicable reason your browser does too...

So let's take this poster-child for browser bloat and build some cool stuff with it!

We'll use this simple, yet powerful protocol to explore the history of electronic music, all while building an arpeggiator (in the browser!) that talks to a real physical synthesizer.

Let's make some javascript music together!

(will require audio, I can route the synthesizer audio to my laptop, or we should be able to use the external speaker mentioned in the FAQ)

### CODE REVIEW

**Comment by jyeg** [comment]
A JavaScript Symphony :+1:

**Comment by erin-lee** [comment]
:+1: 
james-franco-thumbs-up-e1402410083652

**Comment by jonathanhculver** [comment]
I don't see any tests, could use some test coverage

**Comment by kosamari** [comment]
Yey to everything web audio :tada: 
excited to have you speak at March event :)
Email with details will be sent tonight.

**Pull request closed without merging**
