### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by SaraJo**
Jewelbots are tiny computers that live on your wrist! This open source wearable (the first of its kind!) is full of super powers that are waiting to be unlocked. In 15 minutes we will learn about the different ways to code Jewelbots and awesome things that people are building.

### CODE REVIEW

**Comment by SaraJo** [comment]
Also, this is for Feb, if that is not obvious.

**Comment by willmanduffy** [comment]
Hey @SaraJo we'll be getting JerseyScript'd in Feb and don't have talks. March work for you?

**Comment by SaraJo** [comment]
Perf!

**Comment by SaraJo** [comment]
Also, march is persian new year…but i’ll see what i can do.

**Pull request closed without merging**
